/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [117.36KB] > C:\Users\frede\OneDrive\Images\3D models\stargateTOP\scene-transformed.glb [387.36KB] (-230%)
Author: stale_mud (https://sketchfab.com/stale_mud)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/stargate-1af03ae28595490aa11ce3ba07b1e23f
Title: Stargate
*/

import React from "react"
import { useRef } from "react"
import { useFrame } from "@react-three/fiber"
import { useGLTF } from "@react-three/drei"

const Stargate = React.memo(function Stargate(props) {
  const { nodes, materials } = useGLTF("/models/stargate-transformed.glb")
  const groupRef = useRef()

  useFrame((state, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.z -= delta * 0.1 // Adjust the 0.1 value to change rotation speed
    }
  })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group rotation={[0, -Math.PI / 2, 0]} position={[0, 0, 0]}>
        <mesh
          geometry={nodes.gate_Gate_0.geometry}
          material={materials.Gate}
          // position={[0, 0, 0]}
          rotation={[-1.571, 1.57, 1.571]}
          scale={0.77}
        />
        <mesh
          geometry={nodes.chevron_Chevron_0.geometry}
          material={materials.Chevron}
          position={[0.354, 2.207, -0.005]}
          rotation={[-1.571, 1.57, 1.571]}
          scale={[0.77, 0.77, 1.432]}
        />
        <mesh
          geometry={nodes.chevron_back_Chevron_unlit_0.geometry}
          material={materials.Chevron_unlit}
          position={[-0.356, 2.207, -0.005]}
          rotation={[1.571, -1.57, 1.571]}
          scale={[-0.77, 0.77, 1.432]}
        />
        <mesh
          geometry={nodes.gate_ring_Ring_0.geometry}
          material={materials.Ring}
          // position={[0, 0, 0]}
          rotation={[-1.571, 1.57, 1.571]}
          scale={0.77}
        />
      </group>
    </group>
  )
})

export default Stargate
useGLTF.preload("/models/stargate-transformed.glb")
